name: rewrite validation
on:
  push:
    branches: [ "main" , "master"]
  pull_request:
    branches: [ "main" , "master"]

jobs:
  check-updates:
    uses: luizleiteoliveira/tutorials/.github/workflows/openrewrite_update_latest.yml@main