name: rewrite validation
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    uses: luizleiteoliveira/tutorials/.github/workflows/openrewrite_update_latest.yml@main